# Server Port
server.port=8080

# H2 In-Memory Database Configurations (Zero configuration needed)
spring.datasource.url=jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console Enablement
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Allow data.sql to run after Hibernate creates tables
spring.sql.init.mode=always

# Uncomment below to configure PostgresSQL database in production
# spring.datasource.url=jdbc:postgresql://localhost:5432/hoteldb
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
